// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwkclhckwmvczbuiqarw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3a2NsaGNrd212Y3pidWlxYXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2Njg4MzUsImV4cCI6MjA3NDI0NDgzNX0.lW7eoejEKByyObCf_P287L1uj7f-2pgD_bjxbJw1FMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});